aubo_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

aubo_position_controllers:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - upperArm_joint
    - foreArm_joint
    - wrist1_joint
    - wrist2_joint
    - wrist3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    shoulder_joint: {trajectory: 0.1, goal: 0.1}
    upperArm_joint: {trajectory: 0.1, goal: 0.1}
    foreArm_joint: {trajectory: 0.1, goal: 0.1}
    wrist1_joint: {trajectory: 0.1, goal: 0.1}
    wrist2_joint: {trajectory: 0.1, goal: 0.1}
    wrist3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  50
  action_monitor_rate: 10

  # state_publish_rate:  50 # Defaults to 50
  # action_monitor_rate: 20 # Defaults to 20
  # hold_trajectory_duration: 0 # Defaults to 0.5

aubo_velocity_controllers:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - upperArm_joint
    - foreArm_joint
    - wrist1_joint
    - wrist2_joint
    - wrist3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    shoulder_joint: {trajectory: 0.1, goal: 0.1}
    upperArm_joint: {trajectory: 0.1, goal: 0.1}
    foreArm_joint: {trajectory: 0.1, goal: 0.1}
    wrist1_joint: {trajectory: 0.1, goal: 0.1}
    wrist2_joint: {trajectory: 0.1, goal: 0.1}
    wrist3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  50
  action_monitor_rate: 10
  gains:
    #!!These values are useable, but maybe not optimal
    shoulder_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    upperArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    foreArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

  # state_publish_rate:  50 # Defaults to 50
  # action_monitor_rate: 20 # Defaults to 20
  # hold_trajectory_duration: 0 # Defaults to 0.5